name: Sync Fork

on:
  push:
    branches: [setting/#2-deploy] # main 브랜치에 push될 때 실행

jobs:
  sync:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout organization repo
        uses: actions/checkout@v4
        with:
          token: ${{ secrets.SYNC_TOKEN }}
          fetch-depth: 0

      - name: Push to fork
        run: |
          git remote add fork https://${{ secrets.SYNC_TOKEN }}@github.com/suki186/FE.git
          git push fork setting/#2-deploy:test --force
